services:
  prometheus-prod:
    image: prom/prometheus:latest
    container_name: prometheus-prod
    ports:
      - "9091:9090"
    volumes:
      - ./prom-prod.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
  prometheus-dev:
    image: prom/prometheus:latest
    container_name: prometheus-dev
    ports:
      - "9092:9090"
    volumes:
      - ./prom-dev.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
