apiVersion: 1

datasources:
  - name: PromQL Proxy
    type: prometheus
    access: proxy
    url: http://promql-proxy:8081
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
